{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-mtls-password
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "${artifactId}.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.certManager.keystorePassword | quote }}
{{- end }}
